[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"

[font]
size = 11

[font.offset]
x = 1
y = 1

[font.normal]
family = "Rec Mono Casual"
style = "Regular"

[scrolling]
history = 10000

[window]
dynamic_padding = true
dynamic_title = true
opacity = 1

[window.padding]
x = 2
y = 1
