[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"

[font]
size = 11

[font.bold]
family = "Rec Mono Casual"
style = "Bold"

[font.bold_italic]
family = "Rec Mono Casual"
style = "Bold Italic"

[font.italic]
family = "Rec Mono Casual"
style = "Italic"

[font.normal]
family = "Rec Mono Casual"
style = "Regular"

# [font.bold]
# family = "Rec Mono Casual"
# style = "Bold"
#
# [font.bold_italic]
# family = "Rec Mono Casual"
# style = "Bold Italic"
#
# [font.italic]
# family = "Rec Mono Casual"
# style = "Italic"
#
# [font.normal]
# family = "Rec Mono Casual"
# style = "Regular"

[scrolling]
history = 10000

[window]
dynamic_padding = true
dynamic_title = true
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 3
y = 3
